---
- hosts: webservers
  become:true
  tasks:
   -name: install packages
    yum:
   - name: install packages
      yum:
         name: "httpd"
         state: "present"
    - name: Start Apache server
        service:
           name: httpd
           state: started
           enabled: True
     - name: Deploy static website
          copy:
           src: index.html
           dest:/var/www/html/ 
 ...
